### PR TITLE
Added pre-commit hook for linting

### PR DESCRIPTION
**Pull request by karthikiyengar**
This PR adds a basic pre-commit hook that runs `eslint --fix` on `.js` and `.md` files. Unfixable errors need to be fixed before a commit can be performed.

We can also consider doing a `npm run spec:build` as a pre-push hook.

Please let me know if anything else is necessary.

### CODE REVIEW

**Comment by evilsoft** [comment]
@karthikiyengar what OS on you on?
@dalefrancis88 if you get a chance could you pull down this branch, edit some file and explicitly make a change that will make eslint 😭. Both a fixable and a non fixable. Then try to commit it (w/o pushing it up of course). See what happens on your Windows setup.

**Comment by evilsoft** [comment]
@karthikiyengar works like a charm on POSIX for both Linux and Mac OSX.
I give this PR a 👍 but will let @dalefrancis88 give the final approval if he is okay with it on Windows.

**Comment by karthikiyengar** [comment]
I've tested it on a Mac at the moment.

**Comment by dalefrancis88** [comment]
Will check it out and let you know

**Comment by dalefrancis88** [comment]
🚀 It works on windows

**Comment by dalefrancis88** [comment]
image

**Pull request merged**
