### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by premithk**
imparative -> imperative

### CODE REVIEW

**Comment by evilsoft** [comment]
👍 have a squirrel.
image

**Comment by evilsoft** [comment]
@premithk do you mind if I add you to the contributors list for documentation?

**Comment by premithk** [comment]
Sure, ill be honored. Thank you, really interested in this lib, though am just a starter in functional programming

-----Original Message-----

**Comment by evilsoft** [comment]
@premithk awesome!
Welcome to FP, it is super fun!
We have a gitter channel [here](https://gitter.im/crocksjs/crocks) if you wanna ask any questions or show off your code or anything really!

**Pull request merged**
