### PR TITLE
Update Import path for 'merge' module-name

### PR DESCRIPTION
**Pull request by BasantPandey**
Update import path for 'merge' module-name from 'crocks/Pair/merge'  to 'crocks/pointfree/merge'.

### CODE REVIEW

**Comment by evilsoft** [comment]
@BasantPandey Thanks for getting these in. Sorry it took so long to get these going into master.

If you would like, for all the hard work you have done on the docs, feel free to follow these instructions on this PR to add yourself to the Contributors list:
https://github.com/evilsoft/crocks/blob/master/CONTRIBUTORS.md#taking-credit

**Comment by BasantPandey** [comment]
Sorry Post this message too late. I was setting up  my dev environment. I got this error and I could not proceed further. 

```Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/win32-x64-67_binding.node":```

This file no longer exist in this location. 

image

**Comment by dalefrancis88** [comment]
I've seen this before when changes have been made to node. Rimraf your node_modules in both docs and root and re-run `npm run setup`

**Comment by evilsoft** [comment]
@BasantPandey can you run `yarn setup` or `npm run setup`?
That should get you a clean install on everything.

**Comment by BasantPandey** [comment]
@evilsoft  I am using ```npm``` and used the same step as mentioned in the document  ```npm run setup``` https://github.com/evilsoft/crocks/blob/master/CONTRIBUTORS.md#taking-credit.

1. I used the ```npm run setup``` a couple of times but did not worked for me. I will check with Yarn.

**Comment by evilsoft** [comment]
hmmm. Are you on windows but running it in a linux shell?
Looks like you are using bash, but it is expecting something from win64 for the sass binary.

**Comment by BasantPandey** [comment]
Yes I am using window 10 and running all these commands on windows. Can you quickly check on your machine are you able to ran this command on your machine ''"npm i sass@4.9.4'’"
 The error occurred because 4.9.4 versoin no longer exit.

**Comment by BasantPandey** [comment]
I think I need to check which node version compatible with sass@4.9.4 version.
 https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#running-with-sudo-or-as-root

**Comment by BasantPandey** [comment]
It takes lots of time to setup the environment.
1. Node js 10.13.0 version 
2. Update java SDK inorder to compile .soy files.

**Comment by BasantPandey** [comment]
Kindly review it and process it. Thanks

**Pull request merged**
