### PR TITLE
Add `mapReduce` helper function

### PR DESCRIPTION
**Pull request by evilsoft**
## Straight off the press (well the gitter anyhow)

image

A conversation on the gitter with @amsross showed how useful a function like `mapReduce` can be. This PR just implements it.

### CODE REVIEW

**Comment by evilsoft** [comment]
image

**Comment by amsross** [comment]
I wouldn't guess this warrants its own release, but is there a general release timeline in which merged PRs can be expected to become available on npm?

**Comment by evilsoft** [comment]
I was going to try to get the new `ReaderT`, but I can totally cut `0.7.1` tonight.
Not a problem!
Release Early, Release Often.

**Comment by amsross** [comment]
Awesome stuff, btw. I was able to use `mapReduce` immediately. I thought there would be a closer-to-the-monoid solution, but once I pulled it in and used it, it became apparent that this was about as simple as one could hope for!

**Pull request merged**
