### PR TITLE
Ultimate Chore - Bring docs to coding standards : Part 1

### PR DESCRIPTION
**Pull request by dalefrancis88**
This PR is to painstakingly search through the docs and ensure that they're up to the standards we've begun to know and love mostly around formatting. This focuses on line beginning and endings and spellings.

I want to valid the code and fix links on seperate PRS

### CODE REVIEW

**Comment by evilsoft** [comment]
Oh my goodness, gonna take a bit to 👀  all these changes.
Starting now!

**Comment by dalefrancis88** [comment]
Yeah all good, it had to be done sooner or later :) saves people finding random ones if we just go do it ourselves in one big go

After this its code and imports and links and then the coding standards

**Comment by dalefrancis88** [comment]
@bennypowers maybe give this one some 👀 to if you get a chance mate

**Comment by evilsoft** [comment]
image

**Pull request merged**
